### ISSUE TITLE
BottomNavigationBarでtab_viewを使ったタブから違うタブに遷移するとエラーが表示されます

### ISSUE THREAD

**Issue by y-yk-0701** [cb-cloud/flutter_infinite_scroll_tab_view#10]
現在、関わっているアプリのリプレイスでこちらのパッケージを使わせていただきたいと考えておりますが、次のようなエラーが出ておりますので、同様の問題が起きていないかアドバイス等もらえたらと思います🙏

## 起きている状況
- BottomNavigationBarのホームにあたる画面でflutter_infinite_scroll_tab_viewを実装
- その画面から**BottomNavigationBarの違うタブに遷移するとエラーが表示される**
- ただし、クラッシュや見た目上の問題ではなく、エラーが表示されるのみ
- このパッケージを使ってここ１ヶ月ほどリプレイス作業に入っているのですが、ここ数日で今回のエラーが出るようになりました
- ここ数日の差分で思いつくこととしては、Flutterのバージョンを上げたことです
### 補足
- BottomNavigationBarのうち、flutter_infinite_scroll_tab_viewを使っていない画面から、同じくflutter_infinite_scroll_tab_viewを使っていない画面に遷移しても、今回のエラーは出ません
- BottomNavigationBarのうち、flutter_infinite_scroll_tab_viewを使っていない画面から、flutter_infinite_scroll_tab_viewを使っている画面に遷移しても、今回のエラーは出ません

## エラーの内容
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4153:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4167:6)
#2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4193:12)
#3      TickerMode.getNotifier (package:flutter/src/widgets/ticker_provider.dart:96:50)
#4      SingleTickerProviderStateMixin._updateTickerModeNotifier (package:flutter/src/widgets/ticker_provider.dart:246:56)
#5      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:199:5)
#6      new AnimationController (package:flutter/src/animation/animation_controller.dart:246:21)
#7      InnerInfiniteScrollTabViewState._indicatorAnimationController (package:infinite_scroll_tab_view/src/inner_infinite_scroll_tab_view.dart:98:7)
#8      InnerInfiniteScrollTabViewState._indicatorAnimationController (package:infinite_scroll_tab_view/src/inner_infinite_scroll_tab_view.dart)
#9      InnerInfiniteScrollTabViewState.dispose (package:infinite_scroll_tab_view/src/inner_infinite_scroll_tab_view.dart:384:5)
#10     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4983:11)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1926:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#19     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1924:7)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4807:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#27     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#28     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1935:25)
#29     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2519:15)
#30     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2932:7)
#31     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
#32     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#33     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#34     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#35     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#39     _invoke (dart:ui/hooks.dart:151:10)
#40     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#41     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
```
## 環境
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by Kurogoma4D** [comment]
@y-yk-0701 
反応遅れまして申し訳ありません 🙇 
こちら時間が取れ次第確認させていただきます！
もうすでに解決されているかもしれませんが、`BottomNavigationBar` のコンテンツとして表示しているWidgetに `AutomaticKeepAliveClientMixin` を使うと一旦エラーは出なくなるかと思います。

**Comment by y-yk-0701** [comment]
@Kurogoma4D 
こちらこそ、バタバタしておりまして返信遅くなってしまいました、すみません。
ご教示ありがとうございました！実はこちらのパッケージを使わせていただき、下記のサービスを先月末にリリースしておりました。非常に助かりました、ありがとうございます。
https://apps.apple.com/us/app/rippletalk-%E3%83%AA%E3%83%83%E3%83%97%E3%83%AB%E3%83%88%E3%83%BC%E3%82%AF/id1639712124
